name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Install dependencies
        run: bun install
      - name: Build
        run: bun run build
      - name: Create release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          generate_release_notes: true
          files: |
            dist/bitbucket-mcp-server-darwin-arm64.tar.gz
            dist/bitbucket-mcp-server-darwin-x64.tar.gz
            dist/bitbucket-mcp-server-linux-arm64.tar.gz
            dist/bitbucket-mcp-server-linux-x64.tar.gz
            dist/bitbucket-mcp-server-windows-x64.tar.gz
