name: release
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    uses: ./.github/actions/setup
    steps:
      - run: bun run test
  build:
    name: Build
    runs-on: ubuntu-latest
    uses: ./.github/actions/setup
    steps:
      - run: bun run build && ls ${{ github.workspace }}