name: release
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - run: bun run test
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - run: bun run build
        run: |
          ls ${{ github.workspace }}